### PR TITLE
Diagnostics update

### PR DESCRIPTION
**Pull request by pestOO**
Added log4cxx features short description
Update to opensource links

Related issue(s): APPLINK-26662, APPLINK-26096, APPLINK-26781

### CODE REVIEW

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/12305f2004fb0c5fd5bfb6ff944e095e73e06a0c/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/f78e13f4b4896eb5d8e58555f8936199b9413aa4/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/057d39180bd7d58097b64a6eb089dcab2f3529c5/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/486510c10c8e198e77522c295fc048ca9d56b2cc/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/d10fdcdd23b77fd4157d8325304fa8b9d816700a/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/41809673a082e8f5a7879ba25423ec7d5bce78ea/overview/

**Comment by pestOO** [comment]
@AGaliuzov, @AnastasiyaBritanova, please review

**Comment by AGaliuzov** [comment]
Reviewed

**Comment by AnastasiyaBritanova** [comment]
@pestOO , reviewed.

**Pull request merged**
