### PR TITLE
Change Coding style for Core

### PR DESCRIPTION
**Pull request by pestOO**
Update Development View, References, History
Related issue(s): APPLINK-26096, APPLINK-26662

### CODE REVIEW

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/7c777782289ed056719b1810392631c87f7948b8/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/0e509d85663396a8bcba137ec1bd12f4cbcc2fae/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/aec1dbec6074f68e874e8f066996fb0267beac90/overview/

**Comment by pestOO** [comment]
@AByzhynar, @LuxoftAKutsan, please review

**Comment by AByzhynar** [comment]
Reviewed

**Comment by pestOO** [comment]
@LuxoftAKutsan on vacation

**Comment by pestOO** [comment]
@AGaliuzov, please review

**Pull request merged**
