### PR TITLE
Add Use Case View chapter

### PR DESCRIPTION
**Pull request by pestOO**
Removed Use Cases from Case Background
All other architectural views re-numbered in chapter 4 
Related issues: APPLINK-26662, APPLINK-26096

### CODE REVIEW

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/6496e4aee859028991ed23c838fd7d9a8073fd06/overview/

**Comment by pestOO** [comment]
@AnastasiyaBritanova, please review

**Comment by AnastasiyaBritanova** [comment]
@pestOO , please also remove the diagrams that were transferred - from "Case Background" section.

**Comment by AnastasiyaBritanova** [comment]
reviewed.

**Comment by pestOO** [comment]
@AnastasiyaBritanova , right! Thanks)

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/d80b2c3b008bb3997adb698d0b095780b518ffb1/overview/

**Pull request merged**
