### PR TITLE
Update History for august 2016 changes

### PR DESCRIPTION
**Pull request by pestOO**
Added history for #5, #7, #8 and #10 changes.

*Note:* This branch base on changes from #9.

### CODE REVIEW

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/09b313bd8dc073cd3788868fc2e709f2d25b0851/overview/

**Comment by pestOO** [comment]
@AnastasiyaBritanova, @levchenkoS, please review

**Comment by LevchenkoS** [comment]
@pestOO, reviewed.

**Comment by AnastasiyaBritanova** [comment]
@pestOO , not quite clear - how is this change history correlated with SAD releases on gitHub? Perhaps, further to reference the PRs that implement the described changes? Also, is it possible to reference the release that includes the them?

**Comment by AnastasiyaBritanova** [comment]
reviewed.

**Comment by pestOO** [comment]
@AnastasiyaBritanova,
1. History chapter is not merged in developer yet and I've prepared a separate one for avoiding a lot of rebates.  
All next changes need to be send in PR with a History chapter update.
2. It's internal version of SAD.
3. Each SLD releases will be delivered with a correct version of SAD (as a link to the repo or directly to the portal)
4. In future on the Portal will be a feature to select master/develop/release_XX branch documentation and it will be clear for end-user.

**Pull request merged**
