### PR TITLE
Add History chapter

### PR DESCRIPTION
**Pull request by pestOO**
Added changes and approves history
Related issue(s): APPLINK-26662, APPLINK-26096

### CODE REVIEW

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/f9c0a556a242bc7754f7fefd56e51f1a54e4582e/overview/

Error - Traceback (most recent call last):
  File &quot;/var/django/livio/docs/tasks/docdown.py&quot;, line 36, in build_docdown_docs
    config = json.load(data_file)
  File &quot;/usr/lib/python2.7/json/__init__.py&quot;, line 290, in load
    **kw)
  File &quot;/usr/lib/python2.7/json/__init__.py&quot;, line 338, in loads
    return _default_decoder.decode(s)
  File &quot;/usr/lib/python2.7/json/decoder.py&quot;, line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File &quot;/usr/lib/python2.7/json/decoder.py&quot;, line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 59 column 17 (char 1610)

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/0fe55fce3feb718238036f70679755b7d849818a/overview/

**Comment by justinjdickow** [comment]
Preview this pull request at https://smartdevicelink.com/en/guides/pull_request/52f790fe962cc8b8774055d846ee27ba5af96ad7/overview/

**Comment by pestOO** [comment]
@mghiumiusliu, please review

**Comment by mghiumiusliu** [comment]
Do you plan to sync document version with official sdl_core_guide release or it will have its internal versioning also?

**Comment by pestOO** [comment]
@mghiumiusliu,
SAD has own version history.
During release procedure SAD need to approved and increase major version with link in `Approve` table.

**Comment by mghiumiusliu** [comment]
Reviewed

**Pull request merged**
