### PR TITLE
ATF SW Architecture Document 

### PR DESCRIPTION
**Pull request by pestOO**
Automated Test Framework (ATF) SW Architecture Documents.

Please,  review the document. with  **_the last link in this PR_**.
Follow _Left menu_ -> _ATF_ -> _Table of contents_

Related issue(s): [APPLINK-16160](https://adc.luxoft.com/jira/browse/APPLINK-16160)

### CODE REVIEW

**Comment by pestOO** [comment]
@joeygrover,
How to enable a test-server for review Guildes changes?

**Comment by pestOO** [comment]
@joeygrover, @ssmereka, Test server stops showing images at all.
You can follow last link and looks at any image.
Is it possible to fix it?

**Comment by ssmereka** [comment]
Can you please post a link to a location in your files where there is an image and a link to the build server (you referenced this as the "test server") where the image is not showing up.  Thanks, we will try to fix any bugs quickly.

Sorry, I would normally track this down myself, but we are super overloaded at the moment.

**Comment by pestOO** [comment]
@ssmereka,
Generally (as I see) ALL pictures are not shown on the test server.
Example:
PNG  source - https://github.com/pestOO/sdl_core_guides/blob/feature/ATF_SAD/docs/ATF/Solution%20Overview/assets/overview.png
Github shows it well - https://github.com/pestOO/sdl_core_guides/blob/feature/ATF_SAD/docs/ATF/Solution%20Overview/index.md
Test server - https://smartdevicelink.com/en/guides/pull_request/42bcca6f4b5aa703ea1194568b44b559b670fa23/atf/solution-overview/

*P.S.:* Even pictures from [the master are not show](https://smartdevicelink.com/en/guides/pull_request/42bcca6f4b5aa703ea1194568b44b559b670fa23/software-architecture-document/use-case-view/).

**Comment by pestOO** [comment]
@ssmereka,
Thank you. Everything works great.

**Comment by pestOO** [comment]
@AByzhynar, @AGaliuzov, @anosach-luxoft, please, merge.
Reviewed - https://adc.luxoft.com/confluence/x/eUpVEg
Approved - https://adc.luxoft.com/jira/browse/APPLINK-31326

**Comment by pestOO** [comment]
@AByzhynar, @AGaliuzov, @anosach-luxoft, kindly remind you

**Comment by pestOO** [comment]
@AByzhynar, @AGaliuzov, @anosach-luxoft, @LuxoftAKutsan kindly remind you

**Pull request merged**
